name: Compara Templates

on:
  workflow_call:

jobs:
  compara_diretorios:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repositório atual
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0
        ref: ${{ github.ref }}
        ssh-key: ${{ secrets.GLOBAL_SSH }}

    - name: Checa mensagem do commit
      id: commit_message
      run: |
        echo "commit_message=$(git log -1 --pretty=%B)" >> $GITHUB_ENV
        echo "branch_name=$(git log -1 --pretty=%B)" >> $GITHUB_ENV
        echo "new_branch_name=$(git log -1 --pretty=%B)-AUTO" >> $GITHUB_ENV
        
    
    - id: verifica_branch
      uses: GuillaumeFalourd/branch-exists@v1.1
      with:
        branch: ${{ steps.commit_message.outputs.branch_name }}
      

    - if: steps.verifica_branch.outputs.exists == 'false'
      run: |
          echo "Branch $BRANCH_NAME não existe."
          echo "branch_exists=false" >> $GITHUB_ENV

    - name: Criar Nova Branch 
      if: steps.verifica_branch.outputs.exists == 'true'
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.email "rtech.thiago@gmail.com"
        git config --global user.name ${{ github.actor }} 
        
        git fetch origin
        git checkout $branch_name 
        git checkout -b $new_branch_name
        git commit --allow-empty -m "Automation Pipeline"
        git push --set-upstream origin $new_branch_name
    
    - name: Checkout repositório atual
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0
        ref: ${{ env.new_branch_name }}
        ssh-key: ${{ secrets.GLOBAL_SSH }}


    - name: Checkout repositório remoto
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0
        repository: rtechthiago/check-template
        path: remote_actions
        ref: main
        token: ${{ secrets.GLOBAL_TOKEN }}
    
    - name: Checkout repositório remoto
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0
        repository: rtechthiago/template
        path: remote_repo
        ref: main
        token: ${{ secrets.GLOBAL_TOKEN }}

    - name: Configura Ambiente Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
        token: ${{ secrets.GLOBAL_TOKEN }}

    - name: Install dependencies
      run: pip install ruamel.yaml

    - name: Rodando Script de Comparação e Sincronia
      run: |
        python remote_actions/.github/scripts/compare_yaml.py

    - name: Configura workflow
      run: |
        python remote_actions/.github/scripts/set_up_workflow.py

    - name: Checkout New Branch
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0
        clean: 'false'
        ref: ${{ env.new_branch_name }}
        ssh-key: ${{ secrets.GLOBAL_SSH }}

    - name: Faz o push caso tenha alteração
      run: |
        rm -rf remote_repo/ && rm -rf remote_actions/
        git config --global user.name ${{ github.actor }}
        git config --global user.email "rtech.thiago@gmail.com"
        git add .github/
        if [[ $(git status --porcelain) ]]; then
          git commit -m "Sync .github com o diretório remoto [skip ci]"
          git push --set-upstream origin $new_branch_name
        else
          echo "Sem mudanças para comitar"
        fi
    continue-on-error: true
